server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  ignored-services: "*"
  routes:
    administratorClient:
      serviceId: administrator
      path: /administrator/**
    librarianClient:
      serviceId: librarian
      path: /librarian/**
    borrowerClient:
      serviceId: borrower
      path: /borrower/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eureka:
    enabled: true