version: "3"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=library
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - 3307:3306
  web:
      build:
        context: .
        dockerfile: Dockerfile-spring
      image: family:latest
      depends_on:
        - db
      ports:
        - 0:8080
      environment:
        - DATABASE_USER=root
        - DATABASE_PASSWORD=12345678
        - DATABASE_NAME=library
        - DATABASE_PORT=3306